version: "3"

services:
  webapi:
    build: .
    ports:
      - "${OCRD_WEBAPI_PORT}:8000"
    env_file: .env

  mongo:
    image: "mongo"
    ports:
      - "${OCRD_WEBAPI_MONGO_PORT}:27017"
    volumes:
      - "${OCRD_WEBAPI_STORAGE_DIR}/mongo_data:/data/db"

