version: '3.8'

services:
  webapi-rabbit-mq:
    image: rabbitmq
    container_name: ocrd-rabbitmq
    hostname: rabbit-mq-host
    build:
      context: ./ocrd_webapi/rabbitmq
      dockerfile: ./Dockerfile-RabbitMQ
    environment:
      - 'OCRD_WEBAPI_RABBIT_MQ_HOST=${OCRD_WEBAPI_RABBIT_MQ_HOST}'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/etc/:/var/etc/rabbitmq/
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - ocrd-webapi
    healthcheck:
      test: [ "CMD", "nc", "-z", "0.0.0.0", "5672" ]
      interval: 120s
      timeout: 30s
      retries: 5

  webapi:
    build: .
    container_name: ocrd-webapi
    environment:
      - 'OCRD_WEBAPI_SERVER_PATH=${OCRD_WEBAPI_SERVER_PATH}'
      - 'OCRD_WEBAPI_STORAGE_DIR=${OCRD_WEBAPI_STORAGE_DIR}'
      - 'OCRD_WEBAPI_DB_URL=${OCRD_WEBAPI_DB_URL}'
      - 'OCRD_WEBAPI_USERNAME=${OCRD_WEBAPI_USERNAME}'
      - 'OCRD_WEBAPI_PASSWORD=${OCRD_WEBAPI_PASSWORD}'
      - 'OCRD_PROCESSOR_CONFIG_PATH=${OCRD_PROCESSOR_CONFIG_PATH}'
    ports:
      - "${OCRD_WEBAPI_PORT}:8000"
    networks:
      - ocrd-webapi
    volumes:
      - "${OCRD_WEBAPI_DATADIR_HOST}/webapi-data:${OCRD_WEBAPI_STORAGE_DIR}"
      - ./things/processor_config_docker.yml:/processor_config.yml

  mongo:
    image: "mongo"
    container_name: ocrd-mongodb
    ports:
      - "${OCRD_WEBAPI_MONGO_PORT}:27017"
    networks:
      - ocrd-webapi
    volumes:
      - "${OCRD_WEBAPI_DATADIR_HOST}/mongo-data:/data/db"

  ocrd-dummy:
    container_name:
      ocrd-dummy-ps
    build:
      context: .
      dockerfile: things/Dockerfile-Processing-Server
    ports:
      - 5051:5050
    volumes:
      - "${OCRD_WEBAPI_DATADIR_HOST}/webapi-data/workspaces:/workspaces"
    command:
      - "ocrd-dummy"
      - "--address"
      - "0.0.0.0:5050:${OCRD_WEBAPI_DB_URL}"

  ocrd-cis-ocropy-binarize:
    container_name:
      ocrd-cis-ocropy-binarize-ps
    build:
      context: .
      dockerfile: things/Dockerfile-Processing-Server
    ports:
      - 5052:5050
    volumes:
      - "${OCRD_WEBAPI_DATADIR_HOST}/webapi-data/workspaces:/workspaces"
    command:
      - "ocrd-cis-ocropy-binarize"
      - "--address"
      - "0.0.0.0:5050:${OCRD_WEBAPI_DB_URL}"

  ocrd-eynollah-segment:
    container_name:
      ocrd-eynollah-segment-ps
    build:
      context: .
      dockerfile: things/Dockerfile-Processing-Server
    ports:
      - 5053:5050
    volumes:
      - "${OCRD_WEBAPI_DATADIR_HOST}/webapi-data/workspaces:/workspaces"
    command:
      - "ocrd-eynollah-segment"
      - "--address"
      - "0.0.0.0:5050:${OCRD_WEBAPI_DB_URL}"

  ocrd-calamari-recognize:
    container_name:
      ocrd-calamari-recognize-ps
    build:
      context: .
      dockerfile: things/Dockerfile-Processing-Server
    ports:
      - 5054:5050
    volumes:
      - "${OCRD_WEBAPI_DATADIR_HOST}/webapi-data/workspaces:/workspaces"
    command:
      - "ocrd-calamari-recognize"
      - "--address"
      - "0.0.0.0:5050:${OCRD_WEBAPI_DB_URL}"

  ocrd-olena-binarize:
    container_name:
      ocrd-olena-binarize
    build:
      context: .
      dockerfile: things/Dockerfile-Processing-Server
    ports:
      - 5055:5050
    volumes:
      - "${OCRD_WEBAPI_DATADIR_HOST}/webapi-data/workspaces:/workspaces"
    command:
      - "ocrd"
      - "processing-server"
      - "olena-binarize"
      - "--address"
      - "0.0.0.0:5050:${OCRD_WEBAPI_DB_URL}"

networks:
  ocrd-webapi:
    name: ocrd-webapi
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
