services:
  webapi:
    build: .
    ports:
      - "8000:80"
    environment:
      - 'OCRD_WEBAPI_SERVER_PATH=http://141.5.99.53:5050'
      - 'OCRD_WEBAPI_STORAGE_DIR=/ocrd_webapi_data'
      - 'OCRD_WEBAPI_DB_URL=mongodb://mongo:27017/operandi'

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

