version: "3"

services:
  webapi:
    build: .
    ports:
      - "${OCRD_WEBAPI_PORT}:8000"
#    environment:
#      - 'OCRD_WEBAPI_SERVER_PATH=http://localhost:8000'
#      - 'OCRD_WEBAPI_STORAGE_DIR=/ocrd_webapi_data'
#      - 'OCRD_WEBAPI_DB_URL=mongodb://mongo:27017/operandi'

  mongo:
    image: "mongo"
    ports:
      - "${OCRD_WEBAPI_MONGO_PORT}:27017"
    volumes:
      - "${OCRD_WEBAPI_STORAGE_DIR}/mongo_data:/data/db"

